backend:
  name: github
  repo: saladziakcloud/itakura-studio # Twój GitHub
  branch: main
  base_url: https://itakura.studio
  auth_endpoint: /api/auth/login

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Wpisy na bloga"
    folder: "src/content/blog"
    create: true
    fields:
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "pubDate", widget: "datetime"}
      - {label: "Opis", name: "description", widget: "string"}
      - {label: "Zdjęcie wyróżniające", name: "heroImage", widget: "image", required: false}
      - {label: "Treść", name: "body", widget: "markdown"}
